taskExecutor:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 10

spring:
  influxdb:
    url: http://localhost:8086
    username: admin
    password:
    database: ly_test
    retentionPolicy: autogen
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ly_test
  redis:
    host: localhost # Redis服务器地址
    port: 6379      # Redis服务器端口号
    password:       # Redis密码（若有设置则必须提供）
    database: 0     # Redis数据库索引（默认为0）

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTER_IP:localhost}:${REGISTER_PORT:9040}/eureka/
    healthcheck:
      enabled: true