taskExecutor:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 10

spring:
  redis:
    host: localhost # Redis服务器地址
    port: 6379      # Redis服务器端口号
    password:       # Redis密码（若有设置则必须提供）
    database: 0     # Redis数据库索引（默认为0）

upload:
  folder: /Users/liuyan/java/tmp

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTER_IP:localhost}:${REGISTER_PORT:9040}/eureka/
    healthcheck:
      enabled: true