system:
  taskExecutor:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 10

vuser:
  taskExecutor:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 10

qps.optimal: 10

spring:
  redis:
    host: localhost # Redis服务器地址
    port: 6379      # Redis服务器端口号
    password:       # Redis密码 (若有)
    database: 0     # Redis数据库索引
    timeout: 300       # Redis超时时间
    lettuce:
      pool:         # Lettuce连接池配置
        max-active:  100           # 最大活动连接数
        min-idle:    1              # 最小空闲连接数
        max-idle:    10             # 最大空闲连接数
        max-wait:    2000           # 获取连接的最大等待时间
        validationQuery: SELECT 1   # 校验连接是否正常工作的SQL语句

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTER_IP:localhost}:${REGISTER_PORT:9040}/eureka/
    healthcheck:
      enabled: true